src/htdocs/css/_mapView.scss
src/htdocs/css/index.scss

Update styles
- Remove whitespace surrounding tablist. 
- Remove border from tablist-panel. 
- Update leaflet-controls to use 16px spacing.

Update tablist and map styles

---

etc/metadata.js
etc/metadata.json
example/DependencyFactory.html
src/htdocs/js/DependencyFactory.js
test/js/spec/DependencyFactoryTest.js

Update the feed & dependency factory based on feedback from Peter.

Update Dependency Factory

---

src/htdocs/js/AnalysisView.js
test/js/spec/CalculatorTest.js

update broken tests. One was previously broken. The others were broken by an unpdate to the static feed etc/metadata

Test fixes

---

src/htdocs/js/map/LayerControl.js
src/htdocs/js/map/Layers.js

usgs/earthquake-hazard-tool#67

Update overlays to filter based on site class

---

src/htdocs/js/ApplicationView.js
src/htdocs/js/HazardCurveGraphView.js
src/htdocs/js/ResponseSpectrumGraphView.js
src/htdocs/js/SiteClassView.js
src/htdocs/js/TimeHorizonLineView.js

Usgs/earthquake hazard tool#58

---

src/htdocs/js/ApplicationView.js
src/htdocs/js/HazardCurve.js
src/htdocs/js/HazardCurveGraphView.js
src/htdocs/js/HazardResponse.js
src/htdocs/js/ResponseSpectrumGraphView.js

Fixes usgs/earthquake-hazard-tool#66
- Application now has `_curves` collection for current model that is shared across views.
- HazardCurveGraphView selects/deselects curves in collection.
- Manages "imt" and "period" properties for current model based on selected curve in collection.

Usgs/earthquake hazard tool#66

---

src/htdocs/css/_Loader.scss
src/htdocs/css/index.scss
src/htdocs/js/ApplicationView.js
src/htdocs/js/LoaderView.js

fixes usgs/earthquake-hazard-tool#81

Show loader/spinner while calculating results

---

src/lib/db/load.php

These can be re-enabled once the dependency logic is refactored.

Removing data sets that were causing site class issues.

---

src/htdocs/js/TimeHorizonSliderView.js

depends on an update to the hazdev-template
https://github.com/usgs/hazdev-template/pull/114

Change button to be selected instead of disabled

---

gruntconfig/browserify.js

fixes usgs/earthquake-hazard-tool#109

fixes browserify issues when running on windows

---

Gruntfile.js
example/ContourTypeView.html
gruntconfig/browserify.js
gruntconfig/config.js
gruntconfig/connect.js

Some of these don't "need" to be fixed, but I think it is better...

Fix all the things

---

src/htdocs/css/_ActionsView.scss
src/htdocs/css/_AnalysisCollectionView.scss
src/htdocs/css/_ApplicationView.scss
src/htdocs/js/ActionsView.js
src/htdocs/js/AnalysisCollectionView.js

- Add "History" title
- Remove calculate button
- Update delete link

Update ActionsView and AnalysisCollectionView layouts

---

src/htdocs/js/TimeHorizonInputView.js

fixes usgs/earthquake-hazard-tool#96

Remove focus from time horizon input when the model changes

---

src/htdocs/js/ApplicationView.js
src/htdocs/js/Calculator.js
src/htdocs/js/CurveCalculator.js

Fixes usgs/earthquake-hazard-tool#101
- Added CurveCalculator that extends Calculator.
- CurveCalculator sets imt value to 'any'.
- Calculator sets imt value to actual imt value.
- ApplicationView calculator require was changed to require CurveCalculator.

Usgs/earthquake hazard tool#101

---

src/htdocs/js/DeaggregationReportView.js

fixes usgs/earthquake-hazard-tool#105

Change calculateMean, it should be calculating the sum

---

src/htdocs/js/DeaggregationReportView.js

Use exclusive bracket for infinity sign

Bug in DeaggregationReport table header

---

src/htdocs/css/index.scss

fixes https://github.com/usgs/earthquake-hazard-tool/issues/137

Remove empty scss file and references to that file

---

package.json
src/htdocs/_navigation.inc.php
src/htdocs/curve.ws.php
src/htdocs/index.php

textual changes in preparation for release announcement

V0.3.1 rc.1

---

src/htdocs/_navigation.inc.php
src/htdocs/css/_Documentation.scss
src/htdocs/css/index.scss
src/htdocs/documentation.php

This is related to #141 and addresses the user interface documentation.
The data documentation will be added by @pmpowers-usgs 
fixes #141

Add user interface documentation

---

etc/deagg/metadata.js
etc/deagg/metadata.json
src/htdocs/js/DeaggregationReportView.js

fixes https://github.com/usgs/earthquake-hazard-tool/issues/134

fix return period in deaggregation report

---

src/htdocs/css/_AnalysisCollectionView.scss
src/htdocs/js/AnalysisCollectionView.js

fixes https://github.com/usgs/earthquake-hazard-tool/issues/133

When the selected analysis is deleted, select the first analysis in the list

---

src/htdocs/css/_GraphVariables.scss

Update color scheme for bins

---

src/htdocs/js/ApplicationView.js

fixes usgs/earthquake-hazard-tool#148

Making map section initially closed.

---

src/htdocs/js/ApplicationView.js
src/lib/db/load.php
src/lib/db/metadata.php

fixes usgs/earthquake-hazard-tool#147

Changed map section title.

---

src/htdocs/js/ApplicationView.js
src/htdocs/js/DependencyFactory.js
src/htdocs/js/deagg/DeaggOutputView.js
test/js/spec/DependencyFactoryTest.js

Update alert info when deaggregation calculation is not available

---

src/htdocs/css/_ApplicationView.scss
src/htdocs/js/ApplicationView.js
src/htdocs/js/input/InputView.js

Accordion map and header fix

---

package.json
src/htdocs/index.php

fixes #182 
fixes #183 
completes milestone v0.4.1

v0.4.1-rc.0

---

src/htdocs/index.php

fixes usgs/earthquake-hazard-tool#202

Removed beta label from title.

---

src/htdocs/js/map/LayerControl.js

Update hazard map layers

---

src/htdocs/css/_DeaggregationReportView.scss
src/htdocs/js/DeaggregationReportView.js

Improve formatting of deagg report

---

src/htdocs/js/DeaggregationReportView.js

fixes #192 
This will ensure that the deagg report displays properly before and after the changes to the nshmp_haz_ws

Update deagg report to use new fields added by pmpowers

---

src/htdocs/documentation.php
src/htdocs/index.php

Update $contact for application

---

src/htdocs/js/DeaggregationReportView.js

Update Deaggregation Report to use DownloadView

---

src/htdocs/js/Calculator.js
src/htdocs/js/deagg/DeaggCalculator.js

Propagate errors from web service

---

src/htdocs/js/Analysis.js
src/htdocs/js/AnalysisCollectionView.js
src/htdocs/js/AnalysisView.js
src/htdocs/js/ApplicationView.js
src/htdocs/js/Calculator.js
src/htdocs/js/ComponentCurvesGraphView.js
src/htdocs/js/DeaggregationReportView.js
src/htdocs/js/DependencyFactory.js
src/htdocs/js/DynamicHazardResponse.js
src/htdocs/js/HazardCurve.js
src/htdocs/js/HazardCurveGraphView.js
src/htdocs/js/HazardResponse.js
src/htdocs/js/HazardUtil.js

Refactor for coding standards (A-H)

---

README.md

Update readme to point to GitLab.

Add archive information to README
